// src/components/Content.tsx
import React, { FC, ReactNode } from 'react'

interface ContentProps {
  title: string
  children: ReactNode
}

const Content: FC<ContentProps> = ({ title, children }) => {
  return (
    <section className='mx-auto max-w-7xl px-6 sm:px-12 lg:px-32 py-12 sm:py-16 lg:py-20'>
      <h1 className='text-2xl sm:text-3xl lg:text-4xl'>
        <code>~/{title}</code>
      </h1>
      {children}
    </section>
  )
}

export default Content

// src/components/content.svelte
<script lang="ts">
	let { title, children }: { title: string; children: any } = $props();
</script>

<section class="mx-auto max-w-240 px-12 py-12 sm:px-20 sm:py-16 lg:px-40 lg:py-20">
	<h1 class="font-garamond text-2xl text-neutral-50 sm:text-3xl lg:text-3xl">
		{title}
	</h1>
	{@render children()}
</section>
