// src/components/footer.svelte
<script lang="ts">
	import { GithubIcon, MailboxIcon, TwitterIcon } from '@lucide/svelte';

	const socialLinks = [
		{ href: 'mailto:hi@aelpxy.dev', label: 'Email', icon: MailboxIcon },
		{ href: 'https://github.com/aelpxy', label: 'GitHub', icon: GithubIcon },
		{ href: 'https://twitter.com/aelpxy', label: 'Twitter', icon: TwitterIcon }
	];
</script>

<footer
	class="mx-auto mt-2 mb-2 max-w-280 px-6 py-10 sm:px-12 sm:py-16 lg:px-32"
	style="view-transition-name: footer;"
>
	<div
		class="flex flex-col items-center justify-between space-y-4 border-t border-neutral-800 pt-6 sm:flex-row sm:space-y-0 sm:space-x-4 sm:pt-10"
	>
		<a
			rel="noreferrer noopener"
			target="_blank"
			href="https://creativecommons.org/licenses/by-sa/4.0/deed.en"
			title="https://creativecommons.org/licenses/by-sa/4.0/deed.en"
			class="mr-0 text-sm text-neutral-300 transition-transform duration-300 ease-in-out hover:text-neutral-400 sm:text-base"
		>
			© {new Date().getFullYear()} CC BY-SA 4.0 - aelpxy.dev
		</a>

		<div class="flex items-center space-x-4">
			{#each socialLinks as { href, label, icon: Icon } (label)}
				<a
					{href}
					rel="noreferrer noopener"
					target="_blank"
					aria-label={label}
					class="text-neutral-400 transition-all ease-in-out hover:text-neutral-100"
				>
					<Icon size={18} />
				</a>
			{/each}
		</div>
	</div>
</footer>

// src/components/footer.tsx
'use client'

import { motion } from 'motion/react'
import { FaGithub } from 'react-icons/fa6'
import { MdAlternateEmail } from 'react-icons/md'

import Tooltip from '@/components/tooltip'
import { Link } from 'next-view-transitions'

const socialLinks = [
  { href: 'https://github.com/aelpxy', Icon: FaGithub, label: 'GitHub' },
  { href: 'mailto:aelpxy@velta.dev', Icon: MdAlternateEmail, label: 'Email' },
]

const Footer = () => {
  return (
    <motion.footer className='mt-2 border-neutral-800 mx-auto mb-2 px-6 sm:px-12 lg:px-32 py-10 sm:py-16 max-w-[60rem] border'>
      <div className='flex flex-col items-center justify-between pt-6 sm:pt-10 space-y-4 sm:space-y-0 sm:flex-row sm:space-x-4 border-t border-neutral-800'>
        <Tooltip text='https://creativecommons.org/licenses/by-sa/4.0/deed.en'>
          <Link
            rel='noreferrer noopener'
            target='_blank'
            href={'https://creativecommons.org/licenses/by-sa/4.0/deed.en'}
            className='mr-0 transition-transform duration-300 ease-in-out text-sm sm:text-base text-neutral-300 hover:text-neutral-400'
          >
            © {new Date().getFullYear()} - aelpxy.dev
          </Link>
        </Tooltip>

        <div className='flex items-center space-x-4'>
          {socialLinks.map(({ href, Icon, label }, index) => (
            <motion.a
              key={label}
              href={href}
              rel='noreferrer noopener'
              target='_blank'
              aria-label={label}
              className='bg-neutral-900 text-neutral-300 transition-all duration-300 ease-in-out p-2 border border-neutral-700 hover:bg-neutral-800 hover:text-neutral-100'
              transition={{
                duration: 0.3,
                ease: 'easeInOut',
                delay: 0.1 * index,
              }}
            >
              <Icon />
            </motion.a>
          ))}
        </div>
      </div>
    </motion.footer>
  )
}

export default Footer
