// src/components/navbar.svelte
<script lang="ts">
	import { page } from '$app/state';

	const navData = [
		{
			name: 'home',
			href: '/'
		},
		{
			name: 'blog',
			href: '/blog'
		}
	];
</script>

<div class="sticky top-0 z-10 select-none">
	<div class="mx-auto max-w-304 select-none lg:px-32">
		<div
			class="bg-opacity-30 flex w-full items-center justify-between border border-neutral-800 bg-neutral-900/10 px-6 py-4 backdrop-blur-sm backdrop-filter"
		>
			<div>
				<div class="flex select-none lg:flex-1">
					<a href="/" data-sveltekit-preload-data="tap">
						<div class="-m-1.5 p-1.5">
							<span class="sr-only">aelpxy</span>
							<img
								class="h-12 w-auto border-neutral-600"
								src="/favicon.png"
								alt="Icon"
								width="96"
								height="96"
								loading="eager"
								fetchpriority="high"
							/>
						</div>
					</a>
				</div>
			</div>
			<div>
				{#each navData as link (link.name)}
					<a href={link.href} class="px-2.5" data-sveltekit-preload-data="tap">
						<code
							class="px-1.5 py-1 transition-all ease-in-out {page.url.pathname === link.href
								? 'text-neutral-100 underline decoration-wavy'
								: 'text-neutral-400 decoration-wavy hover:underline'}"
						>
							{link.name}
						</code>
					</a>
				{/each}
			</div>
		</div>
	</div>
</div>

// src/components/navbar.tsx
'use client'

import { motion } from 'motion/react'
import { usePathname } from 'next/navigation'

const navData = [
  {
    name: 'home',
    href: '/',
  },
  {
    name: 'blog',
    href: '/blog',
  },
]

import Image from 'next/image'
import Link from 'next/link'

const Navbar = () => {
  const pathname = usePathname()

  return (
    <motion.div className='py-2 select-none sticky top-0 z-10'>
      <div className='mx-auto max-w-[70rem] px-6 lg:px-32 py-2 select-none'>
        <motion.div className='flex w-full items-center justify-between py-4 px-6 rounded-xl bg-stone-900 backdrop-filter bg-opacity-30 backdrop-blur-md'>
          <div>
            <div className='flex lg:flex-1 select-none'>
              <Link href='/'>
                <motion.div
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                  className='-m-1.5 p-1.5'
                >
                  <span className='sr-only'>aelpxy</span>
                  <Image
                    className='h-12 w-auto rounded-md border-stone-600'
                    src={'/favicon.png'}
                    alt='Icon'
                    width={256}
                    height={256}
                  />
                </motion.div>
              </Link>
            </div>
          </div>
          <div>
            {navData.map((link) => (
              <Link key={link.name} href={link.href} className='px-2.5'>
                <motion.code
                  className={`px-1.5 py-1 ease-in-out rounded-md transition-all  ${
                    pathname === link.href
                      ? 'text-stone-100 underline decoration-wavy'
                      : 'text-stone-400 hover:underline decoration-wavy'
                  }`}
                >
                  {link.name}
                </motion.code>
              </Link>
            ))}
          </div>
        </motion.div>
      </div>
    </motion.div>
  )
}

export default Navbar
