// src/app/blog/[slug]/page.tsx
import { notFound } from 'next/navigation'
import * as React from 'react'

import { MDX } from '@/components/mdx'
import { formatDate } from '@/lib/date'
import { getBlogPosts } from '@/lib/markdown'
import { baseUrl } from '@/lib/sitemap'

import Content from '@/components/content'

// @ts-ignore
export default async function Page({ params }) {
  const { slug } = await params

  let post = getBlogPosts().find((post) => post.slug === slug)

  if (!post) {
    notFound()
  }

  return (
    <Content title={post.metadata.title}>
      <article className='prose'>
        {post.metadata.isDraft ? (
          <blockquote>This article is still a work in progress.</blockquote>
        ) : (
          <>
            <div className='flex justify-between items-center mb-8 text-sm'>
              <p className='text-sm text-neutral-400'>
                {formatDate(post.metadata.publishedAt)}
              </p>
            </div>

            {/* @ts-ignore */}
            <MDX source={post.content} />
          </>
        )}
      </article>

      <script
        type='application/ld+json'
        suppressHydrationWarning
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'BlogPosting',
            headline: post.metadata.title,
            datePublished: post.metadata.publishedAt,
            dateModified: post.metadata.publishedAt,
            description: post.metadata.summary,
            url: `${baseUrl}/blog/${post.slug}`,
            author: {
              '@type': 'Person',
              name: 'aelpxy',
            },
          }),
        }}
      />
    </Content>
  )
}

export async function generateStaticParams() {
  let posts = getBlogPosts()

  return posts.map((post) => ({
    slug: post.slug,
  }))
}

// @ts-ignore
export async function generateMetadata({ params }) {
  const { slug } = await params

  let post = getBlogPosts().find((post) => post.slug === slug)

  if (!post) {
    return notFound()
  }

  let ogImage = post.metadata.image
    ? post.metadata.image
    : `${baseUrl}/open-graph?type=blog&title=${encodeURIComponent(post.metadata.title)}&path=~/blog/${post.slug}&date=${formatDate(post.metadata.publishedAt)}`

  return {
    title: post.metadata.title,
    description: post.metadata.summary,
    openGraph: {
      title: post.metadata.title,
      description: post.metadata.summary,
      type: 'article',
      publishedTime: post.metadata.publishedAt,
      url: `${baseUrl}/blog/${post.slug}`,
      images: [
        {
          url: ogImage,
        },
      ],
    },
    twitter: {
      card: 'summary_large_image',
      title: post.metadata.title,
      description: post.metadata.summary,
      images: [ogImage],
    },
  }
}

// src/routes/blog/[slug]/+page.svelte
<script lang="ts">
	import Content from '../../../components/content.svelte';
	import { formatDate } from '$lib/date';

	let { data } = $props();
	const { post } = data;
</script>

<svelte:head>
	<title>{post.metadata.title} - aelpxy</title>
	<meta name="description" content={post.metadata.summary} />

	<!-- Open Graph / Facebook -->
	<meta property="og:type" content="article" />
	<meta property="og:url" content="https://aelpxy.dev/blog/{post.slug}" />
	<meta property="og:title" content={post.metadata.title} />
	<meta property="og:description" content={post.metadata.summary} />
	<meta property="og:site_name" content="aelpxy" />
	<meta property="article:published_time" content={post.metadata.publishedAt} />

	<!-- Twitter -->
	<meta name="twitter:card" content="summary_large_image" />
	<meta name="twitter:url" content="https://aelpxy.dev/blog/{post.slug}" />
	<meta name="twitter:title" content={post.metadata.title} />
	<meta name="twitter:description" content={post.metadata.summary} />

	<!-- Additional Meta Tags -->
	<meta name="author" content="aelpxy" />
	<link rel="canonical" href="https://aelpxy.dev/blog/{post.slug}" />
</svelte:head>

<Content title={post.metadata.title}>
	<article class="prose">
		{#if post.metadata.isDraft}
			<blockquote>This article is still a work in progress.</blockquote>
		{:else}
			<div class="mb-8">
				<p class="text-sm text-neutral-400">
					{formatDate(post.metadata.publishedAt)}
				</p>
			</div>

			<div class="markdown-content">
				{@html post.content}
			</div>
		{/if}
	</article>
</Content>
